key-management-bo:
  http-port: 10080
enigma:
  client:
    two-way-enabled: true
    enigma-base-url: "https://localhost:11443/enigma/"
    # key store
    key-store: enigmaclient.p12
    key-store-password: 2secure4u
    key-store-type: pkcs12
    key-store-alias: enigmaclient
    # trust store
    trust-store: enigmaclient.p12
    trust-store-password: 2secure4u
    trust-store-type: pkcs12
server:
  ssl:
    key-store-type: pkcs12
    key-store-password: 2secure4u
    key-alias: enigmabackoffice
    key-store: classpath:enigmabackoffice.p12

keycloak:
  auth-server-url: http://localhost:12080/auth
  realm: enigma
  resource: enigma-engine
  ssl-required: external
  bearer-only: true
